#!/usr/bin/env bash
# Install the gecko-alpha pre-commit hook chain.
#
# Run once per clone:
#   bash scripts/install-pre-commit-hook.sh
#
# Idempotent — running twice is safe. Writes a dispatcher to
# .git/hooks/pre-commit that calls each hook script in scripts/pre-commit-*.sh
# in order, short-circuiting on the first non-zero exit.
#
# Why a dispatcher instead of a direct symlink: future hooks (linting,
# secret-scan, schema migration check) can be added by dropping
# `scripts/pre-commit-<name>.sh` into the directory and re-running this
# installer. Each hook stays single-purpose and composes without
# cross-script coupling.
#
# Bypass: any individual commit can skip all hooks via `git commit --no-verify`.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="${REPO_ROOT}/.git/hooks/pre-commit"

# Ensure .git/hooks exists (true for any normal clone but guard anyway)
mkdir -p "${REPO_ROOT}/.git/hooks"

cat > "$HOOK_PATH" <<'DISPATCHER_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-pre-commit-hook.sh
# DO NOT EDIT — to add a hook, drop scripts/pre-commit-<name>.sh and re-run
# the installer. To remove a hook, delete the corresponding scripts/pre-commit-*.sh
# and re-run the installer.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Run each scripts/pre-commit-*.sh in alphabetical order.
# First non-zero exit aborts the commit.
shopt -s nullglob
for hook in "${REPO_ROOT}/scripts/pre-commit-"*.sh; do
    bash "$hook" || exit $?
done
exit 0
DISPATCHER_EOF

chmod +x "$HOOK_PATH"

# Also chmod +x all the individual hook scripts (defensive; cross-platform
# clones on Windows sometimes lose +x)
shopt -s nullglob
for hook in "${REPO_ROOT}/scripts/pre-commit-"*.sh; do
    chmod +x "$hook"
done

echo "Installed pre-commit hook dispatcher at $HOOK_PATH"
echo "Active hooks:"
for hook in "${REPO_ROOT}/scripts/pre-commit-"*.sh; do
    echo "  - $(basename "$hook")"
done
